// Code generated by protoc-gen-gonfig. DO NOT EDIT.

package configs

import (
	context "context"
	gonfig "github.com/go-leo/gonfig"
	resource "github.com/go-leo/gonfig/resource"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

var (
	_ApplicationConfig      = &Application{}
	_ApplicationConfigMutex sync.RWMutex
)

func GetApplicationConfig() *Application {
	_ApplicationConfigMutex.RLock()
	cloned := proto.Clone(_ApplicationConfig)
	_ApplicationConfigMutex.RUnlock()
	return cloned.(*Application)
}

func SetApplicationConfig(conf *Application) {
	cloned := proto.Clone(conf).(*Application)
	_ApplicationConfigMutex.Lock()
	_ApplicationConfig = cloned
	_ApplicationConfigMutex.Unlock()
}

func LoadApplicationConfig(ctx context.Context, resource resource.Resource) error {
	conf, err := gonfig.Load[*Application](ctx, resource)
	if err != nil {
		return err
	}
	SetApplicationConfig(conf)
	return nil
}

func WatchApplicationConfig(ctx context.Context, resource resource.Resource) (<-chan struct{}, func(context.Context) error, error) {
	watcher, err := gonfig.Watch[*Application](ctx, resource)
	if err != nil {
		return nil, nil, err
	}
	changedC := make(chan struct{}, 1)
	return changedC, watcher.Stop, nil
}
